[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_BUILDFUTURE = "true"

[context.deploy-preview.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"

# [[plugins]]
# package = "netlify-plugin-hashfiles"
